### ISSUE TITLE
[bug] Releases 0.0.8 will throw an error when starting server

### ISSUE THREAD

**Issue by 653448346** [cmseguin/rollup-plugin-react-scoped-css#41]
npm create vite@latest

use the plugin 

npm run dev

`Cannot find module '/***/node_modules/rollup-plugin-react-scoped-css/dist/ast-program' imported from /***/node_modules/rollup-plugin-react-scoped-css/dist/index.js`

and it's correct in Releases 0.0.7

**Comment by cmseguin** [comment]
Hi, can you give me a little more info regarding your node version and the version of vite you are using :) thank you

**Comment by 653448346** [comment]
> 

node v18.12.1
vite  @latest
can't recurring?

**Comment by 653448346** [comment]
> Hi, can you give me a little more info regarding your node version and the version of vite you are using :) thank you
node v18.12.1
vite @latest
can't recurring?

**Comment by 653448346** [comment]
> Hi, can you give me a little more info regarding your node version and the version of vite you are using :) thank you

node v18.12.1
vite @latest
can't recurring?

**Comment by cmseguin** [comment]
When I was working on 0.8.0 yesterday on the newest version of vite it was working fine. But I will try to reproduce fix this asap.
